name: "get-release-version"
description: "Extract the the release version from the current branch."
author: "ML Tooling <team@mltooling.org>"

inputs:
  branch_prefix:
    description: "Prefix of release branch"
    default: "release/v"
    required: false

outputs:
  release_version:
    description: "Release version based on the release branch name"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "tag"
  color: "blue"
